"""Initial schema with auth hardening tables

Revision ID: f6a9a7be18f0
Revises:
Create Date: 2026-08-21 09:40:43.305904

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "f6a9a7be18f0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Foreign key reference constants
COLONIES_ID_FK = ["colonies.id"]
USERS_ID_FK = ["users.id"]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "colonies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("colony_type", sa.String(length=255), nullable=False),
        sa.Column("age_days", sa.Integer(), nullable=False),
        sa.Column("age_last_updated", sa.Date(), nullable=False),
        sa.Column("current_event", sa.String(length=1000), nullable=True),
        sa.Column("base_complacency", sa.Integer(), nullable=False),
        sa.Column("base_order", sa.Integer(), nullable=False),
        sa.Column("base_productivity", sa.Integer(), nullable=False),
        sa.Column("base_piety", sa.Integer(), nullable=False),
        sa.Column("base_size", sa.Integer(), nullable=False),
        sa.Column("representative_id", sa.Integer(), nullable=True),
        sa.Column("dynasty_outcome", sa.String(length=255), nullable=True),
        sa.Column("complacency_locked", sa.Boolean(), nullable=False),
        sa.Column("order_locked", sa.Boolean(), nullable=False),
        sa.Column("productivity_locked", sa.Boolean(), nullable=False),
        sa.Column("planetary_resources", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["representative_id"],
            ["representatives.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("attempted_at", sa.DateTime(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_login_attempts_username"), "login_attempts", ["username"], unique=False
    )
    op.create_table(
        "representatives",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=255), nullable=False),
        sa.Column("personalities", sa.Text(), nullable=False),
        sa.Column("stats", sa.Text(), nullable=False),
        sa.Column("skills", sa.Text(), nullable=False),
        sa.Column("talents", sa.Text(), nullable=False),
        sa.Column("assigned_to_colony_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_to_colony_id"],
            COLONIES_ID_FK,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "infrastructure",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("colony_id", sa.Integer(), nullable=False),
        sa.Column("infrastructure_type", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["colony_id"], COLONIES_ID_FK, ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "modifiers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("colony_id", sa.Integer(), nullable=False),
        sa.Column("modifier_source_type", sa.String(length=255), nullable=False),
        sa.Column("modifier_stat", sa.String(length=255), nullable=False),
        sa.Column("modifier_value", sa.Integer(), nullable=False),
        sa.Column("modifier_description", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["colony_id"], COLONIES_ID_FK, ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("colony_id", sa.Integer(), nullable=False),
        sa.Column("resource_type", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("abundance", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("discovered_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(["colony_id"], COLONIES_ID_FK, ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "support_upgrades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("colony_id", sa.Integer(), nullable=False),
        sa.Column("upgrade_type", sa.String(length=255), nullable=False),
        sa.Column("custom_stat_choice", sa.String(length=255), nullable=True),
        sa.Column("custom_product", sa.String(length=255), nullable=True),
        sa.Column("affiliated_group", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["colony_id"], COLONIES_ID_FK, ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=True),
        sa.Column("updated_at", sa.Date(), nullable=True),
        sa.Column("managed_colony_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["managed_colony_id"],
            COLONIES_ID_FK,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("field", sa.String(length=100), nullable=True),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("changed_by", sa.Integer(), nullable=False),
        sa.Column("changed_at", sa.DateTime(), nullable=True),
        sa.Column("colony_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            USERS_ID_FK,
        ),
        sa.ForeignKeyConstraint(["colony_id"], COLONIES_ID_FK, ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "colony_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("colony_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=True),
        sa.Column("invited_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["colony_id"], COLONIES_ID_FK, ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            USERS_ID_FK,
        ),
        sa.ForeignKeyConstraint(["user_id"], USERS_ID_FK, ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "development_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("colony_id", sa.Integer(), nullable=False),
        sa.Column("upgrade_type", sa.String(length=50), nullable=False),
        sa.Column("target_name", sa.String(length=200), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("acquisition_plan", sa.Text(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["colony_id"], COLONIES_ID_FK, ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            USERS_ID_FK,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("colony_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["colony_id"], COLONIES_ID_FK, ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            USERS_ID_FK,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], USERS_ID_FK, ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_token_blacklist_token_id"), "token_blacklist", ["token_id"], unique=False
    )
    op.create_index(
        op.f("ix_token_blacklist_user_id"), "token_blacklist", ["user_id"], unique=False
    )
    op.create_table(
        "token_issuance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.String(length=255), nullable=False),
        sa.Column("token_type", sa.String(length=10), nullable=False),
        sa.Column("issued_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], USERS_ID_FK, ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_token_issuance_token_id"), "token_issuance", ["token_id"], unique=False
    )
    op.create_index(op.f("ix_token_issuance_user_id"), "token_issuance", ["user_id"], unique=False)
    op.create_table(
        "event_modifiers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("stat", sa.String(length=50), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_modifiers")
    op.drop_index(op.f("ix_token_issuance_user_id"), table_name="token_issuance")
    op.drop_index(op.f("ix_token_issuance_token_id"), table_name="token_issuance")
    op.drop_table("token_issuance")
    op.drop_index(op.f("ix_token_blacklist_user_id"), table_name="token_blacklist")
    op.drop_index(op.f("ix_token_blacklist_token_id"), table_name="token_blacklist")
    op.drop_table("token_blacklist")
    op.drop_table("events")
    op.drop_table("development_plans")
    op.drop_table("colony_users")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("support_upgrades")
    op.drop_table("resources")
    op.drop_table("modifiers")
    op.drop_table("infrastructure")
    op.drop_table("representatives")
    op.drop_index(op.f("ix_login_attempts_username"), table_name="login_attempts")
    op.drop_table("login_attempts")
    op.drop_table("colonies")
    # ### end Alembic commands ###
